### ISSUE TITLE
Azure Function produce STAC records

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/stactools-palsar#19]
**Describe the bug**
The Azure function currently only makes COGs, and does not generate the STAC item records.

**To reproduce**
Run the Azure function.

**Expected behavior**
We can copy over code from the commands.py portion for create_stac_item
https://github.com/developmentseed/stactools-palsar/blob/63fd9b5b35aa61640d28f10def5c0973109d5d07/src/stactools/palsar/commands.py#L80-L86

**Comment by wildintellect** [comment]
@tracetechnical this is done now?

**Comment by tracetechnical** [comment]
This is done, but hasnt been tested with any of Tom's suggestions.

**Comment by wildintellect** [comment]
Oh that's all just changes to what text is in the json, as long as we now create any json this is done.
