### ISSUE TITLE
Figure out actual extent

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/stactools-palsar#26]
**Is your feature request related to a problem? Please describe.**
We guessed on the spatial extent of the collection. Since @tracetechnical has access to all the downloads, can you look for the Northern most and Southern most items available. Right now I guessed 85N -55S as the extent. East-West is fine as the whole world. 

**Describe the solution you'd like**
Update the extent in the constants.py to better reflect actual coverage which is not documented by JAXA.

**Describe alternatives you've considered**
Defaulting to whole world, but it's clear Antarctica is not covered based on the download website.

**Comment by tracetechnical** [comment]
According to my python script run across all blobs in the input store:
```
maxN:85
maxS:55
maxE:85
maxW:85
```

**Comment by tracetechnical** [comment]
@wildintellect Does this look correct to you?http://bboxfinder.com/#-90.000000,-60.000000,90.000000,90.000000

**Comment by wildintellect** [comment]
The 55S tile is the upper corner, so went with 56S as the extent. Double checked by browsing JAXA download portal.
