### ISSUE TITLE
Add ZIP support

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/stactools-palsar#30]
**Is your feature request related to a problem? Please describe.**
JAXA recently updated all the files on their server to  be ZIP not TAR.GZ

**Describe the solution you'd like**
Code should be able to handle either ZIP or TAR.GZ depending on which version of files are supplied. 

**Additional context**
No other major changes were made. Mask files now come compressed with LZW, but that has 0 impact on existing COG conversion scripts. It apppears older data, 2015, 2016 might now be released in TIFF format instead of ENVI but the code already handled that too.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/developmentseed/stactools-palsar/pull/31 I think.
